apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-1
spec:
  selector:
    matchLabels:
      app: echo-1
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-1
    spec:
      containers:
        - name: echo-1
          image: hashicorp/http-echo
          args:
            - "-text=echo-1"
          ports:
            - containerPort: 5678
